### PR TITLE
Init the Chinese translation and import existing files from a legacy repo

### PR DESCRIPTION
**Pull request by Jinjiang**
For https://github.com/vuejs/v3-migration-guide/issues/18 and https://github.com/vuejs-translations/docs-zh-cn/issues/586 I'd like to init this move.

- I created a `src/zh/` folder to contain all the translation files. It followed the way we maintain the translations for other repos in the Vue ecosystem like [Pinia](https://github.com/vuejs/pinia/tree/v2/packages/docs)
- I just imported existing translations from https://github.com/vuejs/docs-next-zh-cn/tree/master/src/guide/migration however, they look outdated, which need review and update.
- Besides translation review and update, I think there are also some chores to do like adding some Chinese nav links, a translation menu, etc.

And before it's well finished, I will keep this PR as the draft status.

Contribution (to this `translation-zh` branch) welcome!

Thanks.

### CODE REVIEW

**Comment by wxsms** [comment]
Shall we PR to the `translation-zh` branch directly in this repo?

**Comment by Jinjiang** [comment]
> Shall we PR to the `translation-zh` branch directly in this repo?

Yes, feel free to go!

**Comment by Jinjiang** [comment]
I suggest we **resolve all the dead links first**. I will also add a warning on top of the pages to indicate that this is a WIP translation. Just in case there are some outdated information that get people confused.
 
Then I can merge and close this PR. Then we can review and update the translation by small pieces.

Thanks.

**Comment by zhousg** [comment]
> I suggest we **resolve all the dead links first**

ok

**Pull request merged**
