### PR TITLE
feat: Ukrainian language

### PR DESCRIPTION
**Pull request by matrunchyk**
As a maintainer on the [vuejs-translations](https://github.com/vuejs-translations/docs-uk) team, I am pleased to submit this PR that represents the collaborative efforts of our team members, particularly @maxdzin and @OlesyaKlochko who have done the majority of the work. Thank you both for your contributions!

I appreciate your time and consideration in squash-merging this PR. Thank you in advance!

### CODE REVIEW

**Review by NataliaTepluhina — APPROVED** [review]
@matrunchyk thank you for the translation! It took me some time to read and verify but I am happy to approve now 🎉

**Comment by matrunchyk** [comment]
Thanks a lot @NataliaTepluhina!

**Comment by matrunchyk** [comment]
Can someone with write access permissions merge the changes please? 🎆

**Comment by Jinjiang** [comment]
@matrunchyk Done. Nice job!

**Comment by matrunchyk** [comment]
Thanks for approving & merging guys!

**Pull request merged**
